### All credentials
GET http://localhost:3000/api/credentials/
Authorization: {{$dotenv MASTERPASSWORD}}

### Valid credential request
GET http://localhost:3000/api/credentials/google
Authorization: {{$dotenv MASTERPASSWORD}}

### Invalid credential request
GET http://localhost:3000/api/credentials/xyz
Authorization: {{$dotenv MASTERPASSWORD}}

### Invalid credential request
GET http://localhost:3000/api/credentials/google
Authorization: wrongKey

### Add a new credential
POST http://localhost:3000/api/credentials/
Content-Type: application/json
Authorization: {{$dotenv MASTERPASSWORD}}

{
    "service": "deleteme",
    "username": "Eraser",
    "password": "oldPw"
}

###
DELETE http://localhost:3000/api/credentials/deleteme
Authorization: {{$dotenv MASTERPASSWORD}}

### Add a new credential
PUT http://localhost:3000/api/credentials/deleteme
Content-Type: application/json
Authorization: {{$dotenv MASTERPASSWORD}}

{
    "service": "deleteme",
    "username": "neu",
    "password": "neuesPw"
}

### Add basis of DB
POST http://localhost:3000/api/credentials/
Content-Type: application/json
Authorization: {{$dotenv MASTERPASSWORD}}

  {
    "service": "google",
    "username": "g00gle",
    "password": "strongPW"
  },
  {
    "service": "facebook",
    "username": "f4ceb00k",
    "password": "smile"
  },
  {
    "service": "twitter",
    "username": "vogel",
    "password": "peeeep"
  },